export const configs = {
  categories: {
    title: "Danh mục",
    singular: "danh mục",
    id: "categoryId",
    text: "name",
    max: 100,
    descriptionMax: 1000,
    hint: "Tổ chức nội dung theo từng chủ đề.",
  },
  quizzes: {
    title: "Đề thi",
    singular: "đề thi",
    id: "quizId",
    text: "title",
    max: 200,
    descriptionMax: 2000,
    parent: "categories",
    parentKey: "categoryId",
    parentLabel: "Danh mục",
    hint: "Xây dựng và quản lý ngân hàng đề thi.",
  },
  questions: {
    title: "Câu hỏi",
    singular: "câu hỏi",
    id: "questionId",
    text: "content",
    max: 2000,
    parent: "quizzes",
    parentKey: "quizId",
    parentLabel: "Đề thi",
    hint: "Biên soạn câu hỏi và kiểm tra độ hoàn thiện.",
  },
  answers: {
    title: "Đáp án",
    singular: "đáp án",
    id: "answerId",
    text: "content",
    max: 2000,
    parent: "questions",
    parentKey: "questionId",
    parentLabel: "Câu hỏi",
    hint: "Hoàn thiện bốn lựa chọn và xác định đáp án đúng.",
  },
};
export const labelOf = (row) => row.name || row.title || row.content;
