// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizApp.Api.Data;

#nullable disable

namespace QuizApp.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuizApp.Api.Models.Answer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("QuestionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Answers_OneCorrectPerQuestion")
                        .HasFilter("[IsCorrect] = 1");

                    b.ToTable("Answers", (string)null);
                });

            modelBuilder.Entity("QuizApp.Api.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("QuizApp.Api.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("QuizApp.Api.Models.Quiz", b =>
                {
                    b.Property<int>("QuizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuizId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("QuizId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Quizzes", (string)null);
                });

            modelBuilder.Entity("QuizApp.Api.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<DateTime>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<string>("QuizTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("QuizId");

                    b.HasIndex("UserId", "CompletedAt");

                    b.ToTable("Results", null, t =>
                        {
                            t.HasCheckConstraint("CK_Results_Counts", "[TotalQuestions] > 0 AND [CorrectAnswers] >= 0 AND [CorrectAnswers] <= [TotalQuestions]");

                            t.HasCheckConstraint("CK_Results_Score", "[Score] >= 0 AND [Score] <= 100");
                        });
                });

            modelBuilder.Entity("QuizApp.Api.Models.ResultDetail", b =>
                {
                    b.Property<int>("ResultDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultDetailId"));

                    b.Property<string>("CorrectAnswerContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CorrectAnswerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("ResultId")
                        .HasColumnType("int");

                    b.Property<string>("SelectedAnswerContent")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("SelectedAnswerId")
                        .HasColumnType("int");

                    b.HasKey("ResultDetailId");

                    b.HasIndex("CorrectAnswerId", "QuestionId");

                    b.HasIndex("QuestionId", "QuizId");

                    b.HasIndex("ResultId", "QuestionId")
                        .IsUnique();

                    b.HasIndex("ResultId", "QuizId");

                    b.HasIndex("SelectedAnswerId", "QuestionId");

                    b.ToTable("ResultDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_ResultDetails_IsCorrect", "([IsCorrect] = 1 AND [SelectedAnswerId] IS NOT NULL AND [SelectedAnswerId] = [CorrectAnswerId]) OR ([IsCorrect] = 0 AND ([SelectedAnswerId] IS NULL OR [SelectedAnswerId] <> [CorrectAnswerId]))");

                            t.HasCheckConstraint("CK_ResultDetails_Selection", "([SelectedAnswerId] IS NULL AND [SelectedAnswerContent] IS NULL) OR ([SelectedAnswerId] IS NOT NULL AND [SelectedAnswerContent] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("QuizApp.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Student");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] COLLATE Latin1_General_100_BIN2 IN (N'Admin', N'Student')");
                        });
                });

            modelBuilder.Entity("QuizApp.Api.Models.Answer", b =>
                {
                    b.HasOne("QuizApp.Api.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizApp.Api.Models.Question", b =>
                {
                    b.HasOne("QuizApp.Api.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizApp.Api.Models.Quiz", b =>
                {
                    b.HasOne("QuizApp.Api.Models.Category", "Category")
                        .WithMany("Quizzes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QuizApp.Api.Models.Result", b =>
                {
                    b.HasOne("QuizApp.Api.Models.Quiz", "Quiz")
                        .WithMany("Results")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizApp.Api.Models.User", "User")
                        .WithMany("Results")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizApp.Api.Models.ResultDetail", b =>
                {
                    b.HasOne("QuizApp.Api.Models.Answer", "CorrectAnswer")
                        .WithMany("CorrectInDetails")
                        .HasForeignKey("CorrectAnswerId", "QuestionId")
                        .HasPrincipalKey("AnswerId", "QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizApp.Api.Models.Question", "Question")
                        .WithMany("ResultDetails")
                        .HasForeignKey("QuestionId", "QuizId")
                        .HasPrincipalKey("QuestionId", "QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizApp.Api.Models.Result", "Result")
                        .WithMany("Details")
                        .HasForeignKey("ResultId", "QuizId")
                        .HasPrincipalKey("ResultId", "QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizApp.Api.Models.Answer", "SelectedAnswer")
                        .WithMany("SelectedInDetails")
                        .HasForeignKey("SelectedAnswerId", "QuestionId")
                        .HasPrincipalKey("AnswerId", "QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CorrectAnswer");

                    b.Navigation("Question");

                    b.Navigation("Result");

                    b.Navigation("SelectedAnswer");
                });

            modelBuilder.Entity("QuizApp.Api.Models.Answer", b =>
                {
                    b.Navigation("CorrectInDetails");

                    b.Navigation("SelectedInDetails");
                });

            modelBuilder.Entity("QuizApp.Api.Models.Category", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("QuizApp.Api.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ResultDetails");
                });

            modelBuilder.Entity("QuizApp.Api.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("QuizApp.Api.Models.Result", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("QuizApp.Api.Models.User", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
